version: '3'

tasks:
  openfga:
    desc: Generate the openfga module
    cmds:
      - docker run --rm -v "{{.TASKFILE_DIR}}/internal/openfga:/workspace" -w /workspace bufbuild/buf generate

  steampipe:
    desc: Run Docker steampipe image
    deps: [ steampipe-build ]
    cmds:
      - docker compose -f "{{.ROOT_DIR}}/docker/docker-compose.yaml" up -d
      - docker run --rm --network=steampipe-openfga_default -e STEAMPIPE_LOG_LEVEL=trace -it steampipe-openfga

  steampipe-build:
    internal: true
    desc: Build Docker steampipe image
    cmds:
      - docker build -f "{{.ROOT_DIR}}/docker/Dockerfile-steampipe" -t steampipe-openfga "{{.ROOT_DIR}}"
      - echo "✅ Docker image built successfully"

  standalone:
    desc: Build standalone PostgreSQL FDW image
    cmds:
      - for: [14, 15, 16]
        cmd: > 
          docker buildx build 
          --build-arg PG_MAJOR={{.ITEM}}
          --platform linux/amd64,linux/arm64
          --output type=local,dest=build 
          -f "{{.ROOT_DIR}}/docker/Dockerfile-standalone" "{{.ROOT_DIR}}"

  build:
    desc: Build GMR PostgreSQL image
    cmds:
      - for: [15-3.5]
        cmd: > 
          docker buildx build --build-arg POSTGIS_TAG={{.ITEM}}
          --platform linux/amd64 
          -f "{{.ROOT_DIR}}/docker/Dockerfile" 
          -t gaia3d/gmr-postgis 
          "{{.ROOT_DIR}}"

#  standalone:up:
#    desc: Start standalone FDW stack with docker-compose
#    deps: [ standalone ]
#    cmds:
#      - docker compose -f "{{.ROOT_DIR}}/docker/docker-compose-standalone.yaml" up -d
#      - echo "✅ Standalone FDW stack started"
#      - echo ""
#      - echo "Connection info:"
#      - echo "  Host:     localhost"
#      - echo "  Port:     5432"
#      - echo "  Database: steampipe"
#      - echo "  User:     steampipe"
#      - echo "  Password: steampipe"
#      - echo ""
#      - echo "Test connection:"
#      - echo "  psql -h localhost -U steampipe -d steampipe"
#
#  standalone:down:
#    desc: Stop standalone FDW stack
#    cmds:
#      - docker compose -f "{{.ROOT_DIR}}/docker/docker-compose-standalone.yaml" down
#
#  standalone:logs:
#    desc: View standalone FDW logs
#    cmds:
#      - docker compose -f "{{.ROOT_DIR}}/docker/docker-compose-standalone.yaml" logs -f

  testdata:
    desc: Generate test data using testdata.json configuration
    dir: "{{.ROOT_DIR}}/testdata"
    cmds:
      - go run generator.go testdata_generator.go

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  test:integration:
    desc: Run integration tests
    cmds:
      - OPENFGA_API_URL=http://localhost:8080 OPENFGA_STORE_ID={{.OPENFGA_STORE_ID}} go test ./acl/... -v -run Integration
