# ------------------------------------------------------------
# 1단계: steampipe-postgres-fdw + plugin 을 빌드하는 builder
# ------------------------------------------------------------
FROM ubuntu:24.04 as builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        rsync git wget curl \
        postgresql-server-dev-16 \
    && rm -rf /var/lib/apt/lists/*

ARG PLUGIN_NAME=acl
ARG PLUGIN_VERSION="v0.0.1"
ARG PLUGIN_GITHUB_URL=github.com/carped99/steampipe-plugin-openfga
ARG GO_VERSION=1.25.4

# Go 설치
RUN wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
    && rm go${GO_VERSION}.linux-amd64.tar.gz
ENV PATH=/usr/local/go/bin:$PATH

WORKDIR /src

# Steampipe Postgres FDW 설치
RUN git clone --branch v2.1.3 --depth 1 https://github.com/turbot/steampipe-postgres-fdw.git
WORKDIR /src/steampipe-postgres-fdw

# RUN go get "${PLUGIN_GITHUB_URL}"

# RUN make standalone plugin="openfga" plugin_github_url="github.com/carped99/steampipe-plugin-openfga"
