# syntax=docker/dockerfile:1.19.0

# ------------------------------------------------------------
# 1단계: steampipe-postgres-fdw + plugin 을 빌드하는 builder
# ------------------------------------------------------------
ARG GO_VERSION=1.25.4
ARG PG_MAJOR=17
FROM golang:${GO_VERSION} AS go-builder

FROM postgres:${PG_MAJOR} AS pg-builder

ARG TARGETPLATFORM
ARG BUILDPLATFORM

ARG GO_VERSION=1.25.4
ARG PLUGIN_NAME=openfga
ARG PLUGIN_VERSION="v0.0.1"
ARG PLUGIN_GITHUB_URL=github.com/carped99/steampipe-plugin-openfga

# -------------------------------------------------------
# 1. System packages + PostgreSQL dev files
# -------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential ca-certificates \
    postgresql-server-dev-${PG_MAJOR} \
    rsync git wget curl \
    && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------
# 2. Install Go
# -------------------------------------------------------
COPY --from=go-builder /usr/local/go /usr/local/go
#RUN wget https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
#    && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
#    && rm go${GO_VERSION}.linux-amd64.tar.gz
ENV PATH=/usr/local/go/bin:$PATH

# -------------------------------------------------------
# 3. Clone steampipe-postgres-fdw
# -------------------------------------------------------
WORKDIR /src
RUN git clone --depth 1 https://github.com/turbot/steampipe-postgres-fdw.git
WORKDIR /src/steampipe-postgres-fdw

# -------------------------------------------------------
# 4. Build FDW
# -------------------------------------------------------
RUN make standalone \
      plugin="${PLUGIN_NAME}" \
      plugin_version="${PLUGIN_VERSION}" \
      plugin_github_url="${PLUGIN_GITHUB_URL}"

RUN tar -czf steampipe-postgres-fdw-pg${PG_MAJOR}-linux.tar.gz -C ./build-Linux .

FROM scratch AS artifact
ARG PG_MAJOR
COPY --from=pg-builder /src/steampipe-postgres-fdw/steampipe-postgres-fdw-pg${PG_MAJOR}-linux.tar.gz /